import { Feather } from "@expo/vector-icons";

type FeatherName = keyof typeof Feather.glyphMap;

/**
 * Tool category names, in display order — identical to the web app's Tools page.
 */
export const TOOL_CATEGORIES = [
  "Convert",
  "Image Tools",
  "Organize",
  "Edit",
] as const;

export type ToolCategory = (typeof TOOL_CATEGORIES)[number];

/** Which interactive editor a tool opens, if any. */
export type EditorKind = "pdf" | "image" | null;

export interface Tool {
  id: string;
  title: string;
  description: string;
  acceptedFormats: string[];
  maxFileSize: string;
  /** Parsed numeric size in MB for client-side validation. */
  maxFileSizeMB: number;
  buttonText: string;
  dropAreaText: string;
  fileTypeHint: string;
  outputFormat: string;
  category: ToolCategory;
  /** Feather icon used as a fallback when the Lottie animation is unavailable. */
  feather: FeatherName;
  /** Web route (kept for reference / parity). Mobile routes use the tool id. */
  route: string;
  /** Server-side tool type (snake_case) for the gated real backend. */
  serverToolType: string;
  /** True when the tool accepts more than one input file. */
  multiFile: boolean;
  /** True for the PDF merge tool. */
  isMerge: boolean;
  /** Which interactive editor the tool opens (else null = generic flow). */
  editor: EditorKind;
  /** Editor sub-mode for the shared PDF editor. */
  editorMode?: string;
}

function mb(size: string): number {
  const n = parseInt(size.replace(/[^0-9]/g, ""), 10);
  return Number.isFinite(n) ? n : 50;
}

/**
 * All 27 tools, copy/categories ported verbatim from the web app
 * (`src/lib/toolConfig.ts`).
 */
export const tools: Tool[] = [
  // ─── Convert ───────────────────────────────────────────────────────────
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDF documents to editable Word files",
    acceptedFormats: [".pdf"],
    maxFileSize: "50MB",
    maxFileSizeMB: 50,
    buttonText: "Select PDF Files",
    dropAreaText: "Drop your PDF files here",
    fileTypeHint: "Supports: PDF files up to 50MB each",
    outputFormat: "DOCX",
    category: "Convert",
    feather: "file-text",
    route: "/upload/pdf-to-word",
    serverToolType: "pdf_to_word",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Extract data from PDF to Excel spreadsheets",
    acceptedFormats: [".pdf"],
    maxFileSize: "50MB",
    maxFileSizeMB: 50,
    buttonText: "Select PDF Files",
    dropAreaText: "Drop your PDF files here",
    fileTypeHint: "Supports: PDF files up to 50MB each",
    outputFormat: "XLSX",
    category: "Convert",
    feather: "grid",
    route: "/upload/pdf-to-excel",
    serverToolType: "pdf_to_excel",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "pdf-to-powerpoint",
    title: "PDF to PowerPoint",
    description: "Turn your PDF files into editable PowerPoint PPT and PPTX files",
    acceptedFormats: [".pdf"],
    maxFileSize: "50MB",
    maxFileSizeMB: 50,
    buttonText: "Select PDF Files",
    dropAreaText: "Drop your PDF files here",
    fileTypeHint: "Supports: PDF files up to 50MB each",
    outputFormat: "PPTX",
    category: "Convert",
    feather: "monitor",
    route: "/upload/pdf-to-powerpoint",
    serverToolType: "pdf_to_powerpoint",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "pdf-to-images",
    title: "PDF to Images",
    description: "Convert PDF pages to image files",
    acceptedFormats: [".pdf"],
    maxFileSize: "50MB",
    maxFileSizeMB: 50,
    buttonText: "Select PDF Files",
    dropAreaText: "Drop your PDF files here",
    fileTypeHint: "Supports: PDF files up to 50MB each",
    outputFormat: "JPG/PNG",
    category: "Convert",
    feather: "image",
    route: "/upload/pdf-to-images",
    serverToolType: "pdf_to_images",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert Word documents to PDF format",
    acceptedFormats: [".doc", ".docx"],
    maxFileSize: "50MB",
    maxFileSizeMB: 50,
    buttonText: "Select Word Documents",
    dropAreaText: "Drop your Word documents here",
    fileTypeHint: "Supports: DOC, DOCX files up to 50MB each",
    outputFormat: "PDF",
    category: "Convert",
    feather: "file-text",
    route: "/upload/word-to-pdf",
    serverToolType: "word_to_pdf",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert Excel files to PDF format",
    acceptedFormats: [".xls", ".xlsx"],
    maxFileSize: "50MB",
    maxFileSizeMB: 50,
    buttonText: "Select Excel Files",
    dropAreaText: "Drop your Excel files here",
    fileTypeHint: "Supports: XLS, XLSX files up to 50MB each",
    outputFormat: "PDF",
    category: "Convert",
    feather: "grid",
    route: "/upload/excel-to-pdf",
    serverToolType: "excel_to_pdf",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "powerpoint-to-pdf",
    title: "PowerPoint to PDF",
    description: "Make PPT and PPTX slideshows easy to view by converting them to PDF",
    acceptedFormats: [".ppt", ".pptx"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PowerPoint Files",
    dropAreaText: "Drop your PowerPoint files here",
    fileTypeHint: "Supports: PPT, PPTX files up to 100MB each",
    outputFormat: "PDF",
    category: "Convert",
    feather: "monitor",
    route: "/upload/powerpoint-to-pdf",
    serverToolType: "powerpoint_to_pdf",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "html-to-pdf",
    title: "HTML to PDF",
    description: "Convert webpages in HTML to PDF with a click",
    acceptedFormats: [".html", ".htm"],
    maxFileSize: "10MB",
    maxFileSizeMB: 10,
    buttonText: "Select HTML Files",
    dropAreaText: "Drop your HTML files here",
    fileTypeHint: "Supports: HTML, HTM files up to 10MB each",
    outputFormat: "PDF",
    category: "Convert",
    feather: "code",
    route: "/upload/html-to-pdf",
    serverToolType: "html_to_pdf",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "images-to-pdf",
    title: "Images to PDF",
    description: "Create PDF from multiple image files",
    acceptedFormats: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp"],
    maxFileSize: "20MB",
    maxFileSizeMB: 20,
    buttonText: "Select Images",
    dropAreaText: "Drop your images here",
    fileTypeHint: "Supports: JPG, PNG, GIF, BMP, WebP up to 20MB each",
    outputFormat: "PDF",
    category: "Convert",
    feather: "image",
    route: "/upload/images-to-pdf",
    serverToolType: "images_to_pdf",
    multiFile: true,
    isMerge: false,
    editor: null,
  },

  // ─── Image Tools ───────────────────────────────────────────────────────
  {
    id: "resize-images",
    title: "Resize Images",
    description: "Change image dimensions, scale by percentage, or use preset sizes",
    acceptedFormats: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp"],
    maxFileSize: "20MB",
    maxFileSizeMB: 20,
    buttonText: "Select Images",
    dropAreaText: "Drop your images here",
    fileTypeHint: "Supports: JPG, PNG, GIF, BMP, WebP up to 20MB each",
    outputFormat: "Same Format",
    category: "Image Tools",
    feather: "maximize-2",
    route: "/upload/resize-image",
    serverToolType: "resize_images",
    multiFile: false,
    isMerge: false,
    editor: "image",
    editorMode: "resize",
  },
  {
    id: "crop-images",
    title: "Crop Images",
    description: "Cut specific parts of images with freeform or preset ratios",
    acceptedFormats: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp"],
    maxFileSize: "20MB",
    maxFileSizeMB: 20,
    buttonText: "Select Images",
    dropAreaText: "Drop your images here",
    fileTypeHint: "Supports: JPG, PNG, GIF, BMP, WebP up to 20MB each",
    outputFormat: "Same Format",
    category: "Image Tools",
    feather: "crop",
    route: "/upload/crop-image",
    serverToolType: "crop_images",
    multiFile: false,
    isMerge: false,
    editor: "image",
    editorMode: "crop",
  },
  {
    id: "rotate-images",
    title: "Rotate Images",
    description: "Rotate images by any angle with automatic background fill",
    acceptedFormats: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp"],
    maxFileSize: "20MB",
    maxFileSizeMB: 20,
    buttonText: "Select Images",
    dropAreaText: "Drop your images here",
    fileTypeHint: "Supports: JPG, PNG, GIF, BMP, WebP up to 20MB each",
    outputFormat: "Same Format",
    category: "Image Tools",
    feather: "refresh-cw",
    route: "/upload/rotate-image",
    serverToolType: "rotate_images",
    multiFile: false,
    isMerge: false,
    editor: "image",
    editorMode: "rotate",
  },
  {
    id: "convert-image-format",
    title: "Convert Image Format",
    description: "Convert images to JPG, PNG, WebP, GIF, AVIF or TIFF with quality settings",
    acceptedFormats: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp", ".tiff"],
    maxFileSize: "25MB",
    maxFileSizeMB: 25,
    buttonText: "Select Images",
    dropAreaText: "Drop your images here",
    fileTypeHint: "Supports: JPG, PNG, GIF, BMP, WebP, TIFF up to 25MB each",
    outputFormat: "Various Formats",
    category: "Image Tools",
    feather: "refresh-cw",
    route: "/upload/convert-image-format",
    serverToolType: "convert_image_format",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "compress-images",
    title: "Compress Images",
    description: "Reduce image file size without losing quality for web optimization",
    acceptedFormats: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSize: "25MB",
    maxFileSizeMB: 25,
    buttonText: "Select Images",
    dropAreaText: "Drop your images here",
    fileTypeHint: "Supports: JPG, PNG, WebP up to 25MB each",
    outputFormat: "Compressed Images",
    category: "Image Tools",
    feather: "minimize-2",
    route: "/upload/compress-image",
    serverToolType: "compress_images",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "upscale-images",
    title: "Upscale Images",
    description: "Enhance image resolution using AI technology up to 4x",
    acceptedFormats: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSize: "10MB",
    maxFileSizeMB: 10,
    buttonText: "Select Images",
    dropAreaText: "Drop your images here",
    fileTypeHint: "Supports: JPG, PNG, WebP up to 10MB each",
    outputFormat: "High-res Images",
    category: "Image Tools",
    feather: "trending-up",
    route: "/upload/upscale-image",
    serverToolType: "upscale_images",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "remove-background",
    title: "Remove Background",
    description: "Remove image backgrounds automatically using AI technology",
    acceptedFormats: [".jpg", ".jpeg", ".png"],
    maxFileSize: "15MB",
    maxFileSizeMB: 15,
    buttonText: "Select Images",
    dropAreaText: "Drop your images here",
    fileTypeHint: "Supports: JPG, PNG up to 15MB each",
    outputFormat: "PNG with Transparency",
    category: "Image Tools",
    feather: "scissors",
    route: "/upload/remove-background",
    serverToolType: "remove_background",
    multiFile: false,
    isMerge: false,
    editor: null,
  },

  // ─── Organize ──────────────────────────────────────────────────────────
  {
    id: "merge-pdfs",
    title: "PDF Merger",
    description: "Combine multiple PDF files into one",
    acceptedFormats: [".pdf"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PDF Files",
    dropAreaText: "Drop your PDF files here",
    fileTypeHint: "Supports: PDF files up to 100MB each",
    outputFormat: "Merged PDF",
    category: "Organize",
    feather: "copy",
    route: "/upload/merge-pdfs",
    serverToolType: "merge_pdfs",
    multiFile: true,
    isMerge: true,
    editor: null,
  },
  {
    id: "split-pdf",
    title: "PDF Splitter",
    description: "Split PDF into separate pages or sections",
    acceptedFormats: [".pdf"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PDF Files",
    dropAreaText: "Drop your PDF files here",
    fileTypeHint: "Supports: PDF files up to 100MB each",
    outputFormat: "PDF Files",
    category: "Organize",
    feather: "scissors",
    route: "/upload/split-pdf",
    serverToolType: "split_pdf",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate your PDFs the way you need them",
    acceptedFormats: [".pdf"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PDF Files",
    dropAreaText: "Drop your PDF files here",
    fileTypeHint: "Supports: PDF files up to 100MB each",
    outputFormat: "Rotated PDF",
    category: "Organize",
    feather: "rotate-cw",
    route: "/upload/rotate-pdf",
    serverToolType: "rotate_pdf",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "delete-pages-pdf",
    title: "Delete Pages",
    description: "Preview page thumbnails and remove the pages you don't need",
    acceptedFormats: [".pdf"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PDF File",
    dropAreaText: "Drop your PDF file here",
    fileTypeHint: "Supports: PDF files up to 100MB",
    outputFormat: "Updated PDF",
    category: "Organize",
    feather: "file-minus",
    route: "/upload/delete-pages-pdf",
    serverToolType: "delete_pages_pdf",
    multiFile: false,
    isMerge: false,
    editor: "pdf",
    editorMode: "delete-pages",
  },

  // ─── Edit ──────────────────────────────────────────────────────────────
  {
    id: "edit-pdf",
    title: "Edit PDF",
    description: "Add text and images to your PDF right in the browser — no upload needed",
    acceptedFormats: [".pdf"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PDF File",
    dropAreaText: "Drop your PDF file here",
    fileTypeHint: "Supports: PDF files up to 100MB",
    outputFormat: "Edited PDF",
    category: "Edit",
    feather: "edit-2",
    route: "/upload/edit-pdf",
    serverToolType: "edit_pdf",
    multiFile: false,
    isMerge: false,
    editor: "pdf",
    editorMode: "edit",
  },
  {
    id: "compress-pdf",
    title: "Compress PDF",
    description: "Reduce file size while optimizing for maximal PDF quality",
    acceptedFormats: [".pdf"],
    maxFileSize: "200MB",
    maxFileSizeMB: 200,
    buttonText: "Select PDF Files",
    dropAreaText: "Drop your PDF files here",
    fileTypeHint: "Supports: PDF files up to 200MB each",
    outputFormat: "Compressed PDF",
    category: "Edit",
    feather: "archive",
    route: "/upload/compress-pdf",
    serverToolType: "compress_pdf",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
  {
    id: "crop-pdf",
    title: "Crop PDF",
    description: "Trim margins or select a region and crop every page — right in your browser",
    acceptedFormats: [".pdf"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PDF File",
    dropAreaText: "Drop your PDF file here",
    fileTypeHint: "Supports: PDF files up to 100MB",
    outputFormat: "Cropped PDF",
    category: "Edit",
    feather: "crop",
    route: "/upload/crop-pdf",
    serverToolType: "crop_pdf",
    multiFile: false,
    isMerge: false,
    editor: "pdf",
    editorMode: "crop",
  },
  {
    id: "sign-pdf",
    title: "Sign PDF",
    description: "Draw, type or upload a signature and place it anywhere on your PDF",
    acceptedFormats: [".pdf"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PDF File",
    dropAreaText: "Drop your PDF file here",
    fileTypeHint: "Supports: PDF files up to 100MB",
    outputFormat: "Signed PDF",
    category: "Edit",
    feather: "edit-3",
    route: "/upload/sign-pdf",
    serverToolType: "sign_pdf",
    multiFile: false,
    isMerge: false,
    editor: "pdf",
    editorMode: "sign",
  },
  {
    id: "watermark-pdf",
    title: "Add Watermark",
    description: "Stamp text or an image watermark across every page of your PDF",
    acceptedFormats: [".pdf"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PDF File",
    dropAreaText: "Drop your PDF file here",
    fileTypeHint: "Supports: PDF files up to 100MB",
    outputFormat: "Watermarked PDF",
    category: "Edit",
    feather: "award",
    route: "/upload/watermark-pdf",
    serverToolType: "watermark_pdf",
    multiFile: false,
    isMerge: false,
    editor: "pdf",
    editorMode: "watermark",
  },
  {
    id: "add-image-pdf",
    title: "Add Image to PDF",
    description: "Place a logo, photo or stamp on any page and resize it to fit",
    acceptedFormats: [".pdf"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PDF File",
    dropAreaText: "Drop your PDF file here",
    fileTypeHint: "Supports: PDF files up to 100MB",
    outputFormat: "Updated PDF",
    category: "Edit",
    feather: "image",
    route: "/upload/add-image-pdf",
    serverToolType: "add_image_pdf",
    multiFile: false,
    isMerge: false,
    editor: "pdf",
    editorMode: "add-image",
  },
  {
    id: "ocr-pdf",
    title: "OCR PDF",
    description: "Recognise text in scanned PDFs and export selectable text or a searchable PDF",
    acceptedFormats: [".pdf"],
    maxFileSize: "100MB",
    maxFileSizeMB: 100,
    buttonText: "Select PDF File",
    dropAreaText: "Drop your PDF file here",
    fileTypeHint: "Supports: PDF files up to 100MB",
    outputFormat: "Searchable PDF / Text",
    category: "Edit",
    feather: "type",
    route: "/upload/ocr-pdf",
    serverToolType: "ocr_pdf",
    multiFile: false,
    isMerge: false,
    editor: null,
  },
];

/** Lookup map by id. */
export const toolsById: Record<string, Tool> = tools.reduce(
  (acc, t) => {
    acc[t.id] = t;
    return acc;
  },
  {} as Record<string, Tool>,
);

export function getToolById(id?: string | null): Tool | undefined {
  return id ? toolsById[id] : undefined;
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((t) => t.category === category);
}

/**
 * PDF-converter tools featured on the home hero (clicking swaps the hero card
 * on web; on mobile they deep-link straight into the conversion flow).
 */
export const PDF_CONVERTER_IDS = [
  "pdf-to-word",
  "pdf-to-excel",
  "pdf-to-powerpoint",
  "pdf-to-images",
  "word-to-pdf",
  "excel-to-pdf",
  "powerpoint-to-pdf",
  "images-to-pdf",
  "html-to-pdf",
];

export const isHeroTool = (id?: string | null): boolean =>
  !!id && PDF_CONVERTER_IDS.includes(id);

/** Dynamic action-button label per tool (matches the web Tools page). */
export function getToolActionLabel(tool: Tool): string {
  const labels: Record<string, string> = {
    "pdf-to-word": "Convert to Word",
    "pdf-to-excel": "Convert to Excel",
    "pdf-to-powerpoint": "Convert to PowerPoint",
    "pdf-to-images": "Convert to Images",
    "word-to-pdf": "Convert to PDF",
    "excel-to-pdf": "Convert to PDF",
    "powerpoint-to-pdf": "Convert to PDF",
    "html-to-pdf": "Convert to PDF",
    "images-to-pdf": "Convert to PDF",
  };
  return labels[tool.id] ?? tool.title;
}
