name: Builder.io Auto-Sync

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/src/**'
  workflow_dispatch:

jobs:
  notify-replit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Build frontend
        run: |
          cd frontend
          npm run build
          
      - name: Validate build
        run: |
          if [ -d "frontend/dist" ]; then
            echo "✅ Frontend build successful"
            ls -la frontend/dist/
          else
            echo "❌ Frontend build failed"
            exit 1
          fi
          
      - name: Comment on commit
        if: github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: '🚀 Frontend changes detected! Run `./sync-from-github.sh` in your Replit project to pull the latest updates.'
            });