// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/removebg/Landing.tsx": () => import("../components/mockups/removebg/Landing.tsx"),
  "./components/mockups/removebg/ToolPage.tsx": () => import("../components/mockups/removebg/ToolPage.tsx")
};
